name: Docker Image CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # =========================
      # CHECKOUT CODE
      # =========================
      - name: Checkout Repository
        uses: actions/checkout@v4


      # =========================
      # SETUP DOCKER
      # =========================
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # =========================
      # VALIDATE DOCKER COMPOSE
      # =========================
      - name: Validate Docker Compose
        run: docker compose config


      # =========================
      # BUILD CONTAINERS
      # =========================
      - name: Build Docker Containers
        run: docker compose build